# Generated by Django 3.2.8 on 2021-10-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField(max_length=255)),
                ('causes', models.TextField(max_length=255)),
                ('treatment', models.TextField(max_length=255)),
            ],
        ),
    ]
