# Generated by Django 3.2.8 on 2021-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='diseases',
            name='date_confirmed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='causes',
            field=models.CharField(max_length=80),
        ),
    ]
