# Generated by Django 3.2.8 on 2021-11-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211117_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
